services:
  service-mysql:
    image: bitnami/mysql
    ports: 
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=contactcraft
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    volumes:
      - mysql_data:/bitnami/mysql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: